name: 'Docker Build'
description: 'Build Docker image with caching'
inputs:
  push:
    description: 'Push image to registry'
    required: false
    default: 'false'
  tags:
    description: 'Image tags (newline separated)'
    required: true
  platforms:
    description: 'Target platforms'
    required: false
    default: 'linux/amd64'
  registry:
    description: 'Container registry'
    required: false
    default: 'ghcr.io'

outputs:
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}
  metadata:
    description: 'Build metadata'
    value: ${{ steps.build.outputs.metadata }}

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      if: inputs.platforms != 'linux/amd64'
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        load: ${{ inputs.push == 'false' }}
        tags: ${{ inputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
